version: '3.8'

services:
  # 1. The Broker (Redis) - manages the queue. Key for handling load.
  redis:
    image: redis:alpine
    container_name: radcom_redis
    ports:
      - "6379:6379"

  # 2. The Brain (FastAPI) - receives requests and sends them to the queue.
  backend:
    build: .
    container_name: radcom_backend
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ../models:/models
      - ../logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 3. The Muscle (Celery Worker) - does the heavy background work.
  worker:
    build: .
    container_name: radcom_worker
    # run the Worker with log level INFO
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ../models:/models  # needs access to models to load them
      - ../logs:/app/logs
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus:latest
    container_name: radcom_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: radcom_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # 4. The Face (Streamlit) - the user interface.
  frontend:
    build: .
    container_name: radcom_frontend
    command: streamlit run streamlit_app.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend